name: Func Check Schema

on: [pull_request]

jobs:
  check:
    name: Check Schema
    strategy:
      matrix:
        go: [1.20.10]
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: Check that 'func.yaml schema' is up-to-date
        run: make schema-check
