name: Func E2E OnCluster Test

on: [pull_request]

jobs:
  test:
    name: On Cluster Test
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set Environment Variables
        run: |
          echo "KUBECONFIG=${{ github.workspace }}/hack/bin/kubeconfig.yaml" >> "$GITHUB_ENV"
          echo "PATH=${{ github.workspace }}/hack/bin:$PATH" >> "$GITHUB_ENV"
      - uses: actions/checkout@v3
      - uses: ./.github/composite/go-setup
      - uses: imjasonh/setup-ko@v0.6
      - name: Install Binaries
        run: ./hack/install-binaries.sh
      - name: Allocate Cluster
        run: ./hack/allocate.sh
      - name: Setup testing images
        run: ./hack/setup-testing-images.sh
      - name: Install RH pull secrets for KinD cluster
        env:
          RH_REG_USR: ${{ secrets.RH_REG_USR }}
          RH_REG_PWD: ${{ secrets.RH_REG_PWD }}
        run: ./hack/install-pull-secrets.sh
      - name: Deploy Tekton
        run: ./hack/install-tekton.sh
      - name: Deploy Test Git Server
        run: ./hack/install-git-server.sh
      - name: E2E On Cluster Test
        env:
          E2E_RUNTIMES: ""
          FUNC_REPO_REF: ${{ github.event.pull_request.head.repo.full_name }}
          FUNC_REPO_BRANCH_REF: ${{ github.head_ref }}
        run: make test-e2e-on-cluster
      - uses: codecov/codecov-action@v4
        with:
          files: ./coverage.txt
          flags: e2e-test-oncluster
