name: Func E2E Test

on: [pull_request]

jobs:
  test:
    name: E2E Test
    strategy:
      matrix:
        go: [1.20.2]
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: Install Binaries
        run: ./hack/binaries.sh
      - name: Allocate Cluster
        run: ./hack/allocate.sh
      - name: Local Registry
        run: ./hack/registry.sh
      - name: E2E Test
        run: make test-e2e
      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage.txt
          flags: e2e-test
